// Code generated by sqlc. DO NOT EDIT.

package repository

import "github.com/jackc/pgx/v5/pgtype"

type Resource struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
