FROM golang:1.23-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/[[ .ProjectName ]] ./cmd/app

FROM gcr.io/distroless/static-debian12

COPY --from=build /bin/[[ .ProjectName ]] /[[ .ProjectName ]]

EXPOSE 8080 9090

CMD ["/[[ .ProjectName ]]"]
